apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{.Release.Name}}-api
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "{{ include "chart.api.image.url" . }}"
