apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{.Release.Name}}-api
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.global.imageRepositoryHost }}/{{ .Values.global.githubUsername }}/{{ .Values.global.repositoryName }}-api:latest
