apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
spec:
  host: {{.Chart.Name}}.{{.Values.global.domainName}}
  path: /api
  to:
    kind: Service
    name: {{.Chart.Name}}-api
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
