{{- if .Values.api.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-api
  labels:
    app: {{.Release.Name}}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-api
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-api
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default  # or localhost
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault  # or Localhost
      imagePullSecrets:
        - name: {{.Values.global.imagePullSecret}}
      containers:
        - name: {{.Release.Name}}-api
          image: {{.Values.api.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
          command: [ "node" ]
          args: [ "/app/dist/index.js" ]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}