apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Chart.Name}}-api
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-api
    spec:
      containers:
        - name: {{.Chart.Name}}-api
          image: {{ printf "%s/%s-api:%s" .Values.global.githubUsername .Values.global.repositoryName .Values.global.githubSHA | lower }}
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
          command: ["yarn"]
          args: ["start"]
