apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Chart.Name }}-api
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.global.gitRepositoryUri }}
    contextDir: api
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.global.api.baseImage.name }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.global.api.imageStreamTag }}
