apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}-api
  type: ClusterIP
