{{- if .Values.global.api.enabled -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{.Release.Name}}-api
  annotations:
    "helm.sh/resource-policy": keep
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{.Values.global.api.image}}
{{- end -}}