{{- if .Values.global.web.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{.Release.Name}}-web
  labels:
    app: {{.Release.Name}}
  annotations:
    route.openshift.io/termination: "edge"
    haproxy.router.openshift.io/rewrite-target: /
spec:
  ingressClassName: openshift-default
  rules:
    - host: {{.Values.global.ingressHost}}
      http:
        paths:
          - backend:
              service:
                name: {{.Release.Name}}-web
                port:
                  number: 8080
            path: '{{- if eq .Values.global.alias "docs" }}/{{- else }}/labs/{{ .Values.global.alias }}{{- end }}'
            pathType: Prefix
{{- end }}

---

{{- if .Values.global.api.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{.Release.Name}}-api
  labels:
    app: {{.Release.Name}}
  annotations:
    route.openshift.io/termination: "edge"
    haproxy.router.openshift.io/rewrite-target: /api/v1
spec:
  ingressClassName: openshift-default
  rules:
    - host: {{.Values.global.ingressHost}}
      http:
        paths:
          - backend:
              service:
                name: {{.Release.Name}}-api
                port:
                  number: 8080
            path: /labs/{{ .Values.global.alias }}/api/v1
            pathType: Prefix
{{- end }}
