kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
  annotations:
    route.openshift.io/termination: "edge"
spec:
  ingressClassName: openshift-default
  rules:
    - host: {{.Values.global.ingressHost}}
      http:
        paths:
          {{- if .Values.web.image}}
          - backend:
              service:
                name: {{.Release.Name}}-web
                port:
                  number: 8080
            path: {{- if eq .Values.global.alias "docs" }}/{{- else }}/labs/{{ .Values.global.alias }}{{- end }}
            pathType: Prefix
          {{- end }}
          {{- if .Values.api.image }}
          - backend:
              service:
                name: {{.Release.Name}}-api
                port:
                  number: 8080
            path: /labs/{{ .Values.global.alias }}/api/v1
            pathType: Prefix
          {{- end }}
