kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
  annotations:
    route.openshift.io/termination: "edge"
spec:
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name:   {{.Release.Name}}-web
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: {{.Release.Name}}-api
                port:
                  number: 8080
            path: /api/v1
            pathType: ImplementationSpecific