apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-web
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-web
    spec:
      containers:
        - name: {{.Release.Name}}-web
          image: {{ (include "chart.web.imageStreamTag" .) | lower }}
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
          command: ["yarn"]
          args: ["start"]
