apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{.Release.Name}}-web
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ (include "chart.web.imageStreamTag" .) | lower }}
