apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-web
  labels:
    app: {{.Release.Name}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-web
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-web
    spec:
      initContainers:
        - name: prepare-tmp-dir
          image: busybox
          command: ["sh", "-c", "chown -R nginx:nginx /tmp && chmod -R 755 /tmp"]
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
      imagePullSecrets:
        - name: {{.Values.global.imagePullSecret}}
      containers:
        - name: {{.Release.Name}}-web
          image: {{.Values.web.image}}
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
      volumes:
        - name: tmp-dir
          emptyDir: {}
