{{- if .Values.global.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-web
  labels:
    app: {{.Release.Name}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-web
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-web
    spec:
      imagePullSecrets:
        - name: {{.Values.global.imagePullSecret}}
      containers:
        - name: {{.Release.Name}}-web
          image: {{.Values.global.web.image}}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/modules/http/app.conf
              name: nginx-config
              subPath: app.conf
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: nginx-config
          configMap:
            name: {{.Release.Name}}-nginx-config
{{- end -}}