apiVersion: v2
name: lab-6
description: Kubernetes manifests for lab-7
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common/k8s"
