# Build stage
FROM node:19-alpine AS build

WORKDIR /app

COPY package.json .
RUN yarn

COPY . .
RUN yarn build

# Production stage
FROM nginx:1.21-alpine

# Copy build artifacts and Nginx configuration
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
