import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Weather} from "@/components/weather";


export default function Home() {
  return (
    <>
      <Head>
        <title>Weather | Web Sci Lab 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Weather For Programmers</h1>
        </div>

        <div className={styles.center}>
            <Weather />
        </div>

        <div className={styles.grid}>
          <h3> Bottom </h3>
        </div>
      </main>
    </>
  )
}
