global:
  gitRepositoryHost: github.com
  gitRepositoryName: spring-23-websci
  githubUsername: lucienbrule
  imageRepositoryHost: ghcr.io
  domainName: prod.brule.io
  ingressHost: websci.apps.prod.brule.io
  imagePullSecret: regcred

web:
  image: OVERRIDE_ME
  enabled: false
api:
  image: OVERRIDE_ME
  enabled: false