name: Build All

on:
  workflow_dispatch:

jobs:
  trigger-build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build API workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-api.yml',
              ref: context.ref
            });

  trigger-build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Web workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-web.yml',
              ref: context.ref
            });
