name: Build Web

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        lab: ['lab-3']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push API Docker image
        working-directory: ${{ matrix.lab }}/web
        env:
          LAB_NAME: ${{ matrix.lab }}
          IMAGE_TAG: "ghcr.io/${{ github.repository }}/${{matrix.lab}}-web"
          IMAGE_TAG_SHA: "${{ github.sha }}"
        run: |
          IMAGE_TAG_SHA=$(echo "${IMAGE_TAG}:${IMAGE_TAG_SHA}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG_LATEST=$(echo "${IMAGE_TAG}:latest" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_TAG_SHA .
          docker push $IMAGE_TAG_SHA
          docker tag $IMAGE_TAG_SHA $IMAGE_TAG_LATEST
          docker push $IMAGE_TAG_LATEST
