name: Build All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        uses: ./.github/workflows/build-api.yaml

      - name: Build Web
        uses: ./.github/workflows/build-web.yaml
