name: Build API

on:
  workflow_dispatch:


jobs:
  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        lab: ['lab-3']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push API Docker image
        env:
          LAB_NAME: ${{ matrix.lab }}
          IMAGE_TAG: "ghcr.io/${{ github.repository}}/${{matrix.lab}}-api:${{ github.sha }}"
        run: |
          cd $LAB_NAME/api
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          docker tag $IMAGE_TAG ghcr.io/${{ github.repository}}/${{matrix.lab}}-api:latest
          docker push ghcr.io/${{ github.repository}}/${{matrix.lab}}-api:latest
