name: Build All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build API
        uses: ./.github/workflows/build_api.yaml

      - name: Build Web
        uses: ./.github/workflows/build_web.yaml
