name: Deploy Selected Labs to OpenShift

on:
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab: ['lab-3']
    steps:
      - name: Debug labs input
        run: "echo labs: ${{ github.event.inputs.labs }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT}}

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build and push API Docker image
        env:
          LAB_NAME: ${{ matrix.lab }}
          IMAGE_TAG: "ghcr.io/${{ github.repository}}/${{matrix.lab}}-api:${{ github.sha }}"
        run: |
          cd $LAB_NAME/api
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Build and push Web Docker image
        env:
          LAB_NAME: ${{ matrix.lab }}
          IMAGE_TAG: "ghcr.io/${{ github.repository}}/${{matrix.lab}}-web:${{ github.sha }}"
        run: |
          cd $LAB_NAME/web
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Login to OpenShift Cluster
        env:
          OPENSHIFT_API_URL: ${{ secrets.OPENSHIFT_API_URL }}
          SERVICE_ACCOUNT_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        run: |
          oc login $OPENSHIFT_API_URL --token=$SERVICE_ACCOUNT_TOKEN --insecure-skip-tls-verify

      - name: Set OpenShift Project
        env:
          OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
        run: |
          oc project $OPENSHIFT_NAMESPACE


      - name: Deploy Helm chart
        env:
          LAB_NAME: ${{ matrix.lab }}
          API_IMAGE_TAG: "ghcr.io/${{ github.repository}}/${{matrix.lab}}-api:${{ github.sha }}"
          WEB_IMAGE_TAG: "ghcr.io/${{ github.repository}}/${{matrix.lab}}-web:${{ github.sha }}"
        run: |
          cd $LAB_NAME/k8s
          # Set your OpenShift context, project, and any other required configurations
          API_IMAGE_TAG=$(echo $API_IMAGE_TAG | tr '[:upper:]' '[:lower:]')
          WEB_IMAGE_TAG=$(echo $WEB_IMAGE_TAG | tr '[:upper:]' '[:lower:]')

          echo "Deploying $LAB_NAME with API image tag $API_IMAGE_TAG and Web image tag $WEB_IMAGE_TAG"

          helm upgrade --install $LAB_NAME . --set api.image=$API_IMAGE_TAG --set web.image=$WEB_IMAGE_TAG --set global.githubSHA=${{ github.sha }}

          echo "Rollout complete !!! 🎉💯🤠"