name: Deploy Selected Labs to OpenShift

on:
  workflow_run:
    workflows: ["Build API", "Build Web"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab: ['lab-3']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to OpenShift Cluster
        env:
          OPENSHIFT_API_URL: ${{ secrets.OPENSHIFT_API_URL }}
          SERVICE_ACCOUNT_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        run: |
          oc login $OPENSHIFT_API_URL --token=$SERVICE_ACCOUNT_TOKEN --insecure-skip-tls-verify

      - name: Set OpenShift Project
        env:
          OPENSHIFT_NAMESPACE:
